
<div class="btn-toolbar">
    <div class="btn-group mr-2">
        <div >
            <?= $this->tag->form('email/sendAsynchronousEmail') ?>
                <?= $this->tag->submitButton(['Queue Email', 'class' => 'btn btn-primary', 'onclick' => 'handleButtonClick(this)']) ?>
            <?= $this->tag->endForm() ?>
        </div>
    </div>

    <div class="btn-group">
        <div>
            <?= $this->tag->form('email/sendSynchronousEmail') ?>
                <?= $this->tag->submitButton(['Send sync Email', 'class' => 'btn btn-primary', 'onclick' => 'handleButtonClick(this)']) ?>
            <?= $this->tag->endForm() ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    handleButtonClick = button => {
        button.form.submit();
        button.value = 'Sending...';
        document.querySelectorAll('form .btn').forEach(b => b.disabled = true);
    };
</script>
