<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Happycow Paulo Bing - Send Email Buttons</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <div class="card mt-1 mx-auto">
                <div class="card-body">
                    <h5 class="card-title">Email sending with Phalcon</h5>
                    <?php echo $this->getContent(); ?>
                </div>
            </div>
        </div>
    </body>
</html>